name: RUSSIA APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Find ZIP
        run: |
          find . -type f -name "*.zip"

      - name: Build
        run: |
          mkdir project
          unzip -o BIOG-RUSSIA-Launcher-Game-1.1.0.zip -d project
          cd project
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BIOG-RUSSIA-APK
          path: project/**/build/outputs/apk/debug/*.apk
          
